[versions]
kotlin = "2.3.10"
kotlinxSerializationJson = "1.10.0"
kotlinxCoroutines = "1.10.2"
ktor = "3.4.0"
detekt = "2.0.0-alpha.2"
tinyJib = "0.3.0"
ktlint = "14.0.1"
cache4k = "0.14.0"
logbackClassic = "1.5.32"
kotlinLogging = "8.0.01"
axionRelease = "1.21.1"

[libraries]
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktorServerCachingHeaders = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientJava = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
cache4k = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlinLogging" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinKotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
tinyJib = { id = "tel.schich.tinyjib", version.ref = "tinyJib" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
axionRelease = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }
